import { FilmMeta } from './types';

// Film metadata database — ~350 well-known films with director, genres, country, and approximate Letterboxd average
// This enables genre analysis, director loyalty, contrarian scoring, country passports, etc.
// Films matched by lowercase name + year

type FilmKey = string; // "filmname-year"

function k(name: string, year: number): FilmKey {
  return `${name.toLowerCase()}-${year}`;
}

export const FILM_METADATA: Map<string, FilmMeta> = new Map([
  // === CLASSIC HOLLYWOOD ===
  [k("Citizen Kane", 1941), { director: "Orson Welles", genres: ["Drama", "Mystery"], country: "USA", lbAvg: 4.1 }],
  [k("Casablanca", 1942), { director: "Michael Curtiz", genres: ["Drama", "Romance", "War"], country: "USA", lbAvg: 4.2 }],
  [k("The Wizard of Oz", 1939), { director: "Victor Fleming", genres: ["Fantasy", "Musical", "Adventure"], country: "USA", lbAvg: 3.9 }],
  [k("Vertigo", 1958), { director: "Alfred Hitchcock", genres: ["Thriller", "Mystery", "Romance"], country: "USA", lbAvg: 4.2 }],
  [k("Rear Window", 1954), { director: "Alfred Hitchcock", genres: ["Thriller", "Mystery"], country: "USA", lbAvg: 4.3 }],
  [k("Psycho", 1960), { director: "Alfred Hitchcock", genres: ["Horror", "Thriller"], country: "USA", lbAvg: 4.2 }],
  [k("North by Northwest", 1959), { director: "Alfred Hitchcock", genres: ["Thriller", "Adventure"], country: "USA", lbAvg: 4.2 }],
  [k("Sunset Boulevard", 1950), { director: "Billy Wilder", genres: ["Drama", "Film-Noir"], country: "USA", lbAvg: 4.4 }],
  [k("Some Like It Hot", 1959), { director: "Billy Wilder", genres: ["Comedy", "Romance"], country: "USA", lbAvg: 4.2 }],
  [k("The Apartment", 1960), { director: "Billy Wilder", genres: ["Comedy", "Drama", "Romance"], country: "USA", lbAvg: 4.3 }],
  [k("Double Indemnity", 1944), { director: "Billy Wilder", genres: ["Crime", "Drama", "Film-Noir"], country: "USA", lbAvg: 4.2 }],
  [k("Singin' in the Rain", 1952), { director: "Stanley Donen", genres: ["Musical", "Comedy", "Romance"], country: "USA", lbAvg: 4.2 }],
  [k("It's a Wonderful Life", 1946), { director: "Frank Capra", genres: ["Drama", "Fantasy"], country: "USA", lbAvg: 4.2 }],
  [k("12 Angry Men", 1957), { director: "Sidney Lumet", genres: ["Drama", "Crime"], country: "USA", lbAvg: 4.5 }],
  [k("The Night of the Hunter", 1955), { director: "Charles Laughton", genres: ["Thriller", "Film-Noir"], country: "USA", lbAvg: 4.2 }],
  [k("All About Eve", 1950), { director: "Joseph L. Mankiewicz", genres: ["Drama"], country: "USA", lbAvg: 4.2 }],
  [k("The Searchers", 1956), { director: "John Ford", genres: ["Western", "Drama"], country: "USA", lbAvg: 3.8 }],
  [k("Rebel Without a Cause", 1955), { director: "Nicholas Ray", genres: ["Drama"], country: "USA", lbAvg: 3.7 }],
  [k("A Streetcar Named Desire", 1951), { director: "Elia Kazan", genres: ["Drama"], country: "USA", lbAvg: 4.0 }],
  [k("On the Waterfront", 1954), { director: "Elia Kazan", genres: ["Crime", "Drama"], country: "USA", lbAvg: 4.1 }],

  // === NEW HOLLYWOOD / 1970s ===
  [k("The Godfather", 1972), { director: "Francis Ford Coppola", genres: ["Crime", "Drama"], country: "USA", lbAvg: 4.5 }],
  [k("The Godfather Part II", 1974), { director: "Francis Ford Coppola", genres: ["Crime", "Drama"], country: "USA", lbAvg: 4.4 }],
  [k("Apocalypse Now", 1979), { director: "Francis Ford Coppola", genres: ["War", "Drama"], country: "USA", lbAvg: 4.2 }],
  [k("Taxi Driver", 1976), { director: "Martin Scorsese", genres: ["Crime", "Drama", "Thriller"], country: "USA", lbAvg: 4.2 }],
  [k("Goodfellas", 1990), { director: "Martin Scorsese", genres: ["Crime", "Drama"], country: "USA", lbAvg: 4.4 }],
  [k("Raging Bull", 1980), { director: "Martin Scorsese", genres: ["Drama", "Sport"], country: "USA", lbAvg: 4.1 }],
  [k("The Wolf of Wall Street", 2013), { director: "Martin Scorsese", genres: ["Crime", "Comedy", "Drama"], country: "USA", lbAvg: 4.0 }],
  [k("The Departed", 2006), { director: "Martin Scorsese", genres: ["Crime", "Thriller"], country: "USA", lbAvg: 4.2 }],
  [k("Killers of the Flower Moon", 2023), { director: "Martin Scorsese", genres: ["Crime", "Drama", "History"], country: "USA", lbAvg: 3.9 }],
  [k("The Irishman", 2019), { director: "Martin Scorsese", genres: ["Crime", "Drama"], country: "USA", lbAvg: 3.7 }],
  [k("Jaws", 1975), { director: "Steven Spielberg", genres: ["Thriller", "Adventure", "Horror"], country: "USA", lbAvg: 4.1 }],
  [k("Schindler's List", 1993), { director: "Steven Spielberg", genres: ["Drama", "War", "History"], country: "USA", lbAvg: 4.5 }],
  [k("Raiders of the Lost Ark", 1981), { director: "Steven Spielberg", genres: ["Action", "Adventure"], country: "USA", lbAvg: 4.2 }],
  [k("E.T. the Extra-Terrestrial", 1982), { director: "Steven Spielberg", genres: ["Sci-Fi", "Family"], country: "USA", lbAvg: 3.9 }],
  [k("Saving Private Ryan", 1998), { director: "Steven Spielberg", genres: ["War", "Drama"], country: "USA", lbAvg: 4.2 }],
  [k("A Clockwork Orange", 1971), { director: "Stanley Kubrick", genres: ["Crime", "Drama", "Sci-Fi"], country: "UK", lbAvg: 4.1 }],
  [k("2001: A Space Odyssey", 1968), { director: "Stanley Kubrick", genres: ["Sci-Fi", "Adventure"], country: "UK", lbAvg: 4.1 }],
  [k("The Shining", 1980), { director: "Stanley Kubrick", genres: ["Horror"], country: "UK", lbAvg: 4.2 }],
  [k("Full Metal Jacket", 1987), { director: "Stanley Kubrick", genres: ["War", "Drama"], country: "UK", lbAvg: 4.0 }],
  [k("Barry Lyndon", 1975), { director: "Stanley Kubrick", genres: ["Drama", "War"], country: "UK", lbAvg: 4.1 }],
  [k("Eyes Wide Shut", 1999), { director: "Stanley Kubrick", genres: ["Drama", "Mystery", "Thriller"], country: "UK", lbAvg: 3.7 }],
  [k("Dr. Strangelove", 1964), { director: "Stanley Kubrick", genres: ["Comedy", "War"], country: "UK", lbAvg: 4.3 }],
  [k("Chinatown", 1974), { director: "Roman Polanski", genres: ["Mystery", "Thriller", "Crime"], country: "USA", lbAvg: 4.2 }],
  [k("One Flew Over the Cuckoo's Nest", 1975), { director: "Miloš Forman", genres: ["Drama"], country: "USA", lbAvg: 4.3 }],
  [k("Dog Day Afternoon", 1975), { director: "Sidney Lumet", genres: ["Crime", "Drama"], country: "USA", lbAvg: 4.1 }],
  [k("Network", 1976), { director: "Sidney Lumet", genres: ["Drama"], country: "USA", lbAvg: 4.2 }],
  [k("Annie Hall", 1977), { director: "Woody Allen", genres: ["Comedy", "Romance"], country: "USA", lbAvg: 3.9 }],
  [k("Manhattan", 1979), { director: "Woody Allen", genres: ["Comedy", "Drama", "Romance"], country: "USA", lbAvg: 3.9 }],
  [k("The Exorcist", 1973), { director: "William Friedkin", genres: ["Horror"], country: "USA", lbAvg: 3.9 }],
  [k("The French Connection", 1971), { director: "William Friedkin", genres: ["Crime", "Thriller"], country: "USA", lbAvg: 3.8 }],
  [k("Alien", 1979), { director: "Ridley Scott", genres: ["Horror", "Sci-Fi"], country: "UK", lbAvg: 4.2 }],
  [k("Blade Runner", 1982), { director: "Ridley Scott", genres: ["Sci-Fi", "Drama"], country: "USA", lbAvg: 4.0 }],

  // === 1980s-90s AMERICAN ===
  [k("Blade Runner 2049", 2017), { director: "Denis Villeneuve", genres: ["Sci-Fi", "Drama"], country: "USA", lbAvg: 4.0 }],
  [k("Dune", 2021), { director: "Denis Villeneuve", genres: ["Sci-Fi", "Adventure"], country: "USA", lbAvg: 3.9 }],
  [k("Dune: Part Two", 2024), { director: "Denis Villeneuve", genres: ["Sci-Fi", "Adventure"], country: "USA", lbAvg: 4.2 }],
  [k("Arrival", 2016), { director: "Denis Villeneuve", genres: ["Sci-Fi", "Drama"], country: "USA", lbAvg: 4.0 }],
  [k("Sicario", 2015), { director: "Denis Villeneuve", genres: ["Crime", "Thriller"], country: "USA", lbAvg: 3.9 }],
  [k("Prisoners", 2013), { director: "Denis Villeneuve", genres: ["Crime", "Drama", "Thriller"], country: "USA", lbAvg: 4.1 }],
  [k("Pulp Fiction", 1994), { director: "Quentin Tarantino", genres: ["Crime", "Drama"], country: "USA", lbAvg: 4.3 }],
  [k("Kill Bill: Volume 1", 2003), { director: "Quentin Tarantino", genres: ["Action", "Crime"], country: "USA", lbAvg: 4.1 }],
  [k("Inglourious Basterds", 2009), { director: "Quentin Tarantino", genres: ["War", "Adventure"], country: "USA", lbAvg: 4.1 }],
  [k("Django Unchained", 2012), { director: "Quentin Tarantino", genres: ["Western", "Drama"], country: "USA", lbAvg: 4.1 }],
  [k("Once Upon a Time in Hollywood", 2019), { director: "Quentin Tarantino", genres: ["Comedy", "Drama"], country: "USA", lbAvg: 3.6 }],
  [k("Reservoir Dogs", 1992), { director: "Quentin Tarantino", genres: ["Crime", "Thriller"], country: "USA", lbAvg: 4.1 }],
  [k("The Shawshank Redemption", 1994), { director: "Frank Darabont", genres: ["Drama"], country: "USA", lbAvg: 4.5 }],
  [k("Fight Club", 1999), { director: "David Fincher", genres: ["Drama", "Thriller"], country: "USA", lbAvg: 4.3 }],
  [k("Se7en", 1995), { director: "David Fincher", genres: ["Crime", "Thriller"], country: "USA", lbAvg: 4.2 }],
  [k("Zodiac", 2007), { director: "David Fincher", genres: ["Crime", "Drama", "Thriller"], country: "USA", lbAvg: 4.0 }],
  [k("The Social Network", 2010), { director: "David Fincher", genres: ["Drama"], country: "USA", lbAvg: 4.1 }],
  [k("Gone Girl", 2014), { director: "David Fincher", genres: ["Thriller", "Drama"], country: "USA", lbAvg: 4.0 }],
  [k("The Silence of the Lambs", 1991), { director: "Jonathan Demme", genres: ["Crime", "Thriller", "Horror"], country: "USA", lbAvg: 4.3 }],
  [k("Forrest Gump", 1994), { director: "Robert Zemeckis", genres: ["Drama", "Comedy", "Romance"], country: "USA", lbAvg: 4.0 }],
  [k("Back to the Future", 1985), { director: "Robert Zemeckis", genres: ["Sci-Fi", "Adventure", "Comedy"], country: "USA", lbAvg: 4.2 }],
  [k("The Matrix", 1999), { director: "Lana Wachowski", genres: ["Sci-Fi", "Action"], country: "USA", lbAvg: 4.2 }],
  [k("Heat", 1995), { director: "Michael Mann", genres: ["Crime", "Drama", "Thriller"], country: "USA", lbAvg: 4.1 }],
  [k("The Big Lebowski", 1998), { director: "Joel Coen", genres: ["Comedy", "Crime"], country: "USA", lbAvg: 4.0 }],
  [k("Fargo", 1996), { director: "Joel Coen", genres: ["Crime", "Drama", "Thriller"], country: "USA", lbAvg: 4.1 }],
  [k("No Country for Old Men", 2007), { director: "Joel Coen", genres: ["Crime", "Drama", "Thriller"], country: "USA", lbAvg: 4.2 }],
  [k("The Dark Knight", 2008), { director: "Christopher Nolan", genres: ["Action", "Crime", "Drama"], country: "USA", lbAvg: 4.3 }],
  [k("Inception", 2010), { director: "Christopher Nolan", genres: ["Sci-Fi", "Action", "Thriller"], country: "USA", lbAvg: 4.1 }],
  [k("Interstellar", 2014), { director: "Christopher Nolan", genres: ["Sci-Fi", "Drama", "Adventure"], country: "USA", lbAvg: 4.1 }],
  [k("Memento", 2000), { director: "Christopher Nolan", genres: ["Mystery", "Thriller"], country: "USA", lbAvg: 4.2 }],
  [k("Dunkirk", 2017), { director: "Christopher Nolan", genres: ["War", "Drama", "Action"], country: "UK", lbAvg: 3.8 }],
  [k("Oppenheimer", 2023), { director: "Christopher Nolan", genres: ["Drama", "History"], country: "USA", lbAvg: 4.1 }],
  [k("The Truman Show", 1998), { director: "Peter Weir", genres: ["Comedy", "Drama", "Sci-Fi"], country: "USA", lbAvg: 4.2 }],
  [k("Eternal Sunshine of the Spotless Mind", 2004), { director: "Michel Gondry", genres: ["Romance", "Drama", "Sci-Fi"], country: "USA", lbAvg: 4.2 }],
  [k("There Will Be Blood", 2007), { director: "Paul Thomas Anderson", genres: ["Drama"], country: "USA", lbAvg: 4.2 }],
  [k("Phantom Thread", 2017), { director: "Paul Thomas Anderson", genres: ["Drama", "Romance"], country: "USA", lbAvg: 3.8 }],
  [k("Boogie Nights", 1997), { director: "Paul Thomas Anderson", genres: ["Drama"], country: "USA", lbAvg: 4.0 }],
  [k("Magnolia", 1999), { director: "Paul Thomas Anderson", genres: ["Drama"], country: "USA", lbAvg: 4.0 }],
  [k("Licorice Pizza", 2021), { director: "Paul Thomas Anderson", genres: ["Comedy", "Drama", "Romance"], country: "USA", lbAvg: 3.6 }],
  [k("The Master", 2012), { director: "Paul Thomas Anderson", genres: ["Drama"], country: "USA", lbAvg: 3.8 }],

  // === MODERN AMERICAN ===
  [k("Moonlight", 2016), { director: "Barry Jenkins", genres: ["Drama"], country: "USA", lbAvg: 4.1 }],
  [k("If Beale Street Could Talk", 2018), { director: "Barry Jenkins", genres: ["Drama", "Romance"], country: "USA", lbAvg: 3.8 }],
  [k("Get Out", 2017), { director: "Jordan Peele", genres: ["Horror", "Thriller"], country: "USA", lbAvg: 3.9 }],
  [k("Us", 2019), { director: "Jordan Peele", genres: ["Horror", "Thriller"], country: "USA", lbAvg: 3.3 }],
  [k("Lady Bird", 2017), { director: "Greta Gerwig", genres: ["Comedy", "Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Little Women", 2019), { director: "Greta Gerwig", genres: ["Drama", "Romance"], country: "USA", lbAvg: 4.0 }],
  [k("Barbie", 2023), { director: "Greta Gerwig", genres: ["Comedy", "Fantasy"], country: "USA", lbAvg: 3.5 }],
  [k("Hereditary", 2018), { director: "Ari Aster", genres: ["Horror", "Drama"], country: "USA", lbAvg: 3.8 }],
  [k("Midsommar", 2019), { director: "Ari Aster", genres: ["Horror", "Drama"], country: "USA", lbAvg: 3.6 }],
  [k("The Lighthouse", 2019), { director: "Robert Eggers", genres: ["Horror", "Drama"], country: "USA", lbAvg: 3.8 }],
  [k("The Witch", 2015), { director: "Robert Eggers", genres: ["Horror", "Drama"], country: "USA", lbAvg: 3.6 }],
  [k("Everything Everywhere All at Once", 2022), { director: "Daniel Kwan", genres: ["Sci-Fi", "Action", "Comedy"], country: "USA", lbAvg: 4.1 }],
  [k("La La Land", 2016), { director: "Damien Chazelle", genres: ["Musical", "Romance", "Drama"], country: "USA", lbAvg: 4.0 }],
  [k("Whiplash", 2014), { director: "Damien Chazelle", genres: ["Drama", "Music"], country: "USA", lbAvg: 4.4 }],
  [k("The Florida Project", 2017), { director: "Sean Baker", genres: ["Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Anora", 2024), { director: "Sean Baker", genres: ["Drama", "Comedy", "Romance"], country: "USA", lbAvg: 4.1 }],
  [k("Parasite", 2019), { director: "Bong Joon-ho", genres: ["Thriller", "Drama", "Comedy"], country: "South Korea", lbAvg: 4.5 }],
  [k("Mad Max: Fury Road", 2015), { director: "George Miller", genres: ["Action", "Sci-Fi"], country: "Australia", lbAvg: 4.2 }],
  [k("The Grand Budapest Hotel", 2014), { director: "Wes Anderson", genres: ["Comedy", "Drama", "Adventure"], country: "USA", lbAvg: 4.1 }],
  [k("Moonrise Kingdom", 2012), { director: "Wes Anderson", genres: ["Comedy", "Drama", "Romance"], country: "USA", lbAvg: 3.9 }],
  [k("The Royal Tenenbaums", 2001), { director: "Wes Anderson", genres: ["Comedy", "Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Fantastic Mr. Fox", 2009), { director: "Wes Anderson", genres: ["Animation", "Comedy", "Adventure"], country: "USA", lbAvg: 4.1 }],
  [k("Asteroid City", 2023), { director: "Wes Anderson", genres: ["Comedy", "Drama"], country: "USA", lbAvg: 3.1 }],
  [k("Her", 2013), { director: "Spike Jonze", genres: ["Romance", "Drama", "Sci-Fi"], country: "USA", lbAvg: 4.1 }],
  [k("Lost in Translation", 2003), { director: "Sofia Coppola", genres: ["Drama", "Comedy", "Romance"], country: "USA", lbAvg: 3.8 }],
  [k("The Virgin Suicides", 1999), { director: "Sofia Coppola", genres: ["Drama", "Romance"], country: "USA", lbAvg: 3.7 }],
  [k("Boyhood", 2014), { director: "Richard Linklater", genres: ["Drama"], country: "USA", lbAvg: 3.7 }],
  [k("Before Sunrise", 1995), { director: "Richard Linklater", genres: ["Romance", "Drama"], country: "USA", lbAvg: 4.1 }],
  [k("Before Sunset", 2004), { director: "Richard Linklater", genres: ["Romance", "Drama"], country: "USA", lbAvg: 4.2 }],
  [k("Mulholland Drive", 2001), { director: "David Lynch", genres: ["Mystery", "Thriller", "Drama"], country: "USA", lbAvg: 4.1 }],
  [k("Blue Velvet", 1986), { director: "David Lynch", genres: ["Mystery", "Thriller"], country: "USA", lbAvg: 3.9 }],
  [k("Eraserhead", 1977), { director: "David Lynch", genres: ["Horror", "Fantasy"], country: "USA", lbAvg: 3.8 }],
  [k("The Thin Red Line", 1998), { director: "Terrence Malick", genres: ["War", "Drama"], country: "USA", lbAvg: 3.8 }],
  [k("The Tree of Life", 2011), { director: "Terrence Malick", genres: ["Drama", "Fantasy"], country: "USA", lbAvg: 3.6 }],
  [k("Badlands", 1973), { director: "Terrence Malick", genres: ["Crime", "Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Do the Right Thing", 1989), { director: "Spike Lee", genres: ["Drama", "Comedy"], country: "USA", lbAvg: 4.1 }],

  // === FRENCH CINEMA ===
  [k("The 400 Blows", 1959), { director: "François Truffaut", genres: ["Drama", "Coming-of-Age"], country: "France", lbAvg: 4.2 }],
  [k("Breathless", 1960), { director: "Jean-Luc Godard", genres: ["Crime", "Drama"], country: "France", lbAvg: 3.8 }],
  [k("Cleo from 5 to 7", 1962), { director: "Agnès Varda", genres: ["Drama"], country: "France", lbAvg: 4.0 }],
  [k("The Umbrellas of Cherbourg", 1964), { director: "Jacques Demy", genres: ["Musical", "Romance"], country: "France", lbAvg: 4.0 }],
  [k("La Haine", 1995), { director: "Mathieu Kassovitz", genres: ["Crime", "Drama"], country: "France", lbAvg: 4.3 }],
  [k("Amélie", 2001), { director: "Jean-Pierre Jeunet", genres: ["Comedy", "Romance"], country: "France", lbAvg: 4.1 }],
  [k("Portrait of a Lady on Fire", 2019), { director: "Céline Sciamma", genres: ["Romance", "Drama"], country: "France", lbAvg: 4.3 }],
  [k("The Earrings of Madame de...", 1953), { director: "Max Ophüls", genres: ["Drama", "Romance"], country: "France", lbAvg: 4.2 }],
  [k("Au Hasard Balthazar", 1966), { director: "Robert Bresson", genres: ["Drama"], country: "France", lbAvg: 4.1 }],
  [k("Pickpocket", 1959), { director: "Robert Bresson", genres: ["Crime", "Drama"], country: "France", lbAvg: 4.0 }],
  [k("Anatomy of a Fall", 2023), { director: "Justine Triet", genres: ["Drama", "Thriller"], country: "France", lbAvg: 4.0 }],
  [k("The Rules of the Game", 1939), { director: "Jean Renoir", genres: ["Comedy", "Drama"], country: "France", lbAvg: 4.0 }],
  [k("Blue Is the Warmest Colour", 2013), { director: "Abdellatif Kechiche", genres: ["Drama", "Romance"], country: "France", lbAvg: 3.7 }],
  [k("Caché", 2005), { director: "Michael Haneke", genres: ["Drama", "Mystery", "Thriller"], country: "France", lbAvg: 3.7 }],
  [k("Amour", 2012), { director: "Michael Haneke", genres: ["Drama", "Romance"], country: "France", lbAvg: 3.9 }],
  [k("The White Ribbon", 2009), { director: "Michael Haneke", genres: ["Drama", "Mystery"], country: "Austria", lbAvg: 3.8 }],
  [k("Funny Games", 1997), { director: "Michael Haneke", genres: ["Thriller", "Horror", "Crime"], country: "Austria", lbAvg: 3.7 }],

  // === ITALIAN CINEMA ===
  [k("8½", 1963), { director: "Federico Fellini", genres: ["Drama", "Fantasy"], country: "Italy", lbAvg: 4.2 }],
  [k("La Dolce Vita", 1960), { director: "Federico Fellini", genres: ["Drama", "Comedy"], country: "Italy", lbAvg: 4.1 }],
  [k("Bicycle Thieves", 1948), { director: "Vittorio De Sica", genres: ["Drama"], country: "Italy", lbAvg: 4.3 }],
  [k("L'Avventura", 1960), { director: "Michelangelo Antonioni", genres: ["Drama", "Mystery"], country: "Italy", lbAvg: 3.8 }],
  [k("Cinema Paradiso", 1988), { director: "Giuseppe Tornatore", genres: ["Drama"], country: "Italy", lbAvg: 4.3 }],
  [k("The Good, the Bad and the Ugly", 1966), { director: "Sergio Leone", genres: ["Western", "Adventure"], country: "Italy", lbAvg: 4.4 }],
  [k("Once Upon a Time in the West", 1968), { director: "Sergio Leone", genres: ["Western"], country: "Italy", lbAvg: 4.3 }],

  // === JAPANESE CINEMA ===
  [k("Seven Samurai", 1954), { director: "Akira Kurosawa", genres: ["Action", "Drama"], country: "Japan", lbAvg: 4.5 }],
  [k("Rashomon", 1950), { director: "Akira Kurosawa", genres: ["Crime", "Drama", "Mystery"], country: "Japan", lbAvg: 4.2 }],
  [k("Ikiru", 1952), { director: "Akira Kurosawa", genres: ["Drama"], country: "Japan", lbAvg: 4.4 }],
  [k("Yojimbo", 1961), { director: "Akira Kurosawa", genres: ["Action", "Drama"], country: "Japan", lbAvg: 4.2 }],
  [k("High and Low", 1963), { director: "Akira Kurosawa", genres: ["Crime", "Drama", "Thriller"], country: "Japan", lbAvg: 4.4 }],
  [k("Tokyo Story", 1953), { director: "Yasujirō Ozu", genres: ["Drama"], country: "Japan", lbAvg: 4.4 }],
  [k("Late Spring", 1949), { director: "Yasujirō Ozu", genres: ["Drama"], country: "Japan", lbAvg: 4.2 }],
  [k("Spirited Away", 2001), { director: "Hayao Miyazaki", genres: ["Animation", "Fantasy", "Adventure"], country: "Japan", lbAvg: 4.4 }],
  [k("Princess Mononoke", 1997), { director: "Hayao Miyazaki", genres: ["Animation", "Fantasy", "Adventure"], country: "Japan", lbAvg: 4.3 }],
  [k("My Neighbor Totoro", 1988), { director: "Hayao Miyazaki", genres: ["Animation", "Fantasy", "Family"], country: "Japan", lbAvg: 4.1 }],
  [k("Howl's Moving Castle", 2004), { director: "Hayao Miyazaki", genres: ["Animation", "Fantasy", "Adventure"], country: "Japan", lbAvg: 4.2 }],
  [k("The Wind Rises", 2013), { director: "Hayao Miyazaki", genres: ["Animation", "Drama"], country: "Japan", lbAvg: 3.9 }],
  [k("The Boy and the Heron", 2023), { director: "Hayao Miyazaki", genres: ["Animation", "Fantasy", "Adventure"], country: "Japan", lbAvg: 3.7 }],
  [k("Grave of the Fireflies", 1988), { director: "Isao Takahata", genres: ["Animation", "Drama", "War"], country: "Japan", lbAvg: 4.3 }],
  [k("Perfect Blue", 1997), { director: "Satoshi Kon", genres: ["Animation", "Thriller", "Horror"], country: "Japan", lbAvg: 4.2 }],
  [k("Paprika", 2006), { director: "Satoshi Kon", genres: ["Animation", "Sci-Fi", "Fantasy"], country: "Japan", lbAvg: 3.9 }],
  [k("Akira", 1988), { director: "Katsuhiro Otomo", genres: ["Animation", "Sci-Fi", "Action"], country: "Japan", lbAvg: 3.9 }],
  [k("Harakiri", 1962), { director: "Masaki Kobayashi", genres: ["Drama", "Action"], country: "Japan", lbAvg: 4.6 }],
  [k("Woman in the Dunes", 1964), { director: "Hiroshi Teshigahara", genres: ["Drama", "Thriller"], country: "Japan", lbAvg: 4.1 }],
  [k("Tampopo", 1985), { director: "Jūzō Itami", genres: ["Comedy"], country: "Japan", lbAvg: 4.0 }],
  [k("Your Name.", 2016), { director: "Makoto Shinkai", genres: ["Animation", "Romance", "Fantasy"], country: "Japan", lbAvg: 4.0 }],
  [k("Shoplifters", 2018), { director: "Hirokazu Kore-eda", genres: ["Drama", "Crime"], country: "Japan", lbAvg: 4.2 }],
  [k("Still Walking", 2008), { director: "Hirokazu Kore-eda", genres: ["Drama"], country: "Japan", lbAvg: 4.0 }],
  [k("Nobody Knows", 2004), { director: "Hirokazu Kore-eda", genres: ["Drama"], country: "Japan", lbAvg: 4.1 }],
  [k("Drive My Car", 2021), { director: "Ryusuke Hamaguchi", genres: ["Drama"], country: "Japan", lbAvg: 4.0 }],

  // === KOREAN CINEMA ===
  [k("Memories of Murder", 2003), { director: "Bong Joon-ho", genres: ["Crime", "Thriller", "Drama"], country: "South Korea", lbAvg: 4.4 }],
  [k("Mother", 2009), { director: "Bong Joon-ho", genres: ["Crime", "Drama", "Thriller"], country: "South Korea", lbAvg: 4.0 }],
  [k("Snowpiercer", 2013), { director: "Bong Joon-ho", genres: ["Sci-Fi", "Action", "Drama"], country: "South Korea", lbAvg: 3.7 }],
  [k("Oldboy", 2003), { director: "Park Chan-wook", genres: ["Action", "Drama", "Mystery"], country: "South Korea", lbAvg: 4.2 }],
  [k("The Handmaiden", 2016), { director: "Park Chan-wook", genres: ["Thriller", "Romance", "Drama"], country: "South Korea", lbAvg: 4.3 }],
  [k("Decision to Leave", 2022), { director: "Park Chan-wook", genres: ["Romance", "Thriller", "Mystery"], country: "South Korea", lbAvg: 3.8 }],
  [k("Sympathy for Mr. Vengeance", 2002), { director: "Park Chan-wook", genres: ["Crime", "Drama", "Thriller"], country: "South Korea", lbAvg: 3.7 }],
  [k("Burning", 2018), { director: "Lee Chang-dong", genres: ["Mystery", "Drama"], country: "South Korea", lbAvg: 4.0 }],
  [k("Poetry", 2010), { director: "Lee Chang-dong", genres: ["Drama"], country: "South Korea", lbAvg: 4.1 }],
  [k("Peppermint Candy", 1999), { director: "Lee Chang-dong", genres: ["Drama"], country: "South Korea", lbAvg: 4.1 }],
  [k("A Tale of Two Sisters", 2003), { director: "Kim Jee-woon", genres: ["Horror", "Drama", "Mystery"], country: "South Korea", lbAvg: 3.8 }],
  [k("Train to Busan", 2016), { director: "Yeon Sang-ho", genres: ["Horror", "Action", "Thriller"], country: "South Korea", lbAvg: 3.8 }],
  [k("Past Lives", 2023), { director: "Celine Song", genres: ["Romance", "Drama"], country: "South Korea", lbAvg: 4.0 }],
  [k("The Wailing", 2016), { director: "Na Hong-jin", genres: ["Horror", "Mystery", "Thriller"], country: "South Korea", lbAvg: 4.0 }],

  // === HONG KONG / CHINESE CINEMA ===
  [k("In the Mood for Love", 2000), { director: "Wong Kar-wai", genres: ["Romance", "Drama"], country: "Hong Kong", lbAvg: 4.4 }],
  [k("Chungking Express", 1994), { director: "Wong Kar-wai", genres: ["Romance", "Drama", "Comedy"], country: "Hong Kong", lbAvg: 4.2 }],
  [k("Fallen Angels", 1995), { director: "Wong Kar-wai", genres: ["Crime", "Romance", "Drama"], country: "Hong Kong", lbAvg: 4.1 }],
  [k("Happy Together", 1997), { director: "Wong Kar-wai", genres: ["Romance", "Drama"], country: "Hong Kong", lbAvg: 4.1 }],
  [k("Yi Yi", 2000), { director: "Edward Yang", genres: ["Drama", "Family"], country: "Taiwan", lbAvg: 4.4 }],
  [k("A Brighter Summer Day", 1991), { director: "Edward Yang", genres: ["Drama", "Crime"], country: "Taiwan", lbAvg: 4.4 }],
  [k("A City of Sadness", 1989), { director: "Hou Hsiao-hsien", genres: ["Drama", "History"], country: "Taiwan", lbAvg: 4.1 }],
  [k("Crouching Tiger, Hidden Dragon", 2000), { director: "Ang Lee", genres: ["Action", "Fantasy", "Drama"], country: "Taiwan", lbAvg: 3.8 }],
  [k("Hero", 2002), { director: "Zhang Yimou", genres: ["Action", "Adventure", "Fantasy"], country: "China", lbAvg: 3.7 }],

  // === SCANDINAVIAN CINEMA ===
  [k("The Seventh Seal", 1957), { director: "Ingmar Bergman", genres: ["Drama", "Fantasy"], country: "Sweden", lbAvg: 4.2 }],
  [k("Persona", 1966), { director: "Ingmar Bergman", genres: ["Drama", "Psychological"], country: "Sweden", lbAvg: 4.2 }],
  [k("Wild Strawberries", 1957), { director: "Ingmar Bergman", genres: ["Drama"], country: "Sweden", lbAvg: 4.2 }],
  [k("Fanny and Alexander", 1982), { director: "Ingmar Bergman", genres: ["Drama"], country: "Sweden", lbAvg: 4.3 }],
  [k("The Worst Person in the World", 2021), { director: "Joachim Trier", genres: ["Drama", "Comedy", "Romance"], country: "Norway", lbAvg: 3.9 }],

  // === RUSSIAN / EASTERN EUROPEAN ===
  [k("Stalker", 1979), { director: "Andrei Tarkovsky", genres: ["Sci-Fi", "Drama"], country: "Russia", lbAvg: 4.3 }],
  [k("Solaris", 1972), { director: "Andrei Tarkovsky", genres: ["Sci-Fi", "Drama"], country: "Russia", lbAvg: 4.0 }],
  [k("Mirror", 1975), { director: "Andrei Tarkovsky", genres: ["Drama", "Experimental"], country: "Russia", lbAvg: 4.2 }],
  [k("Andrei Rublev", 1966), { director: "Andrei Tarkovsky", genres: ["Drama", "History"], country: "Russia", lbAvg: 4.3 }],
  [k("Come and See", 1985), { director: "Elem Klimov", genres: ["War", "Drama"], country: "Russia", lbAvg: 4.5 }],
  [k("The Double Life of Véronique", 1991), { director: "Krzysztof Kieślowski", genres: ["Drama", "Mystery"], country: "Poland", lbAvg: 4.0 }],
  [k("Three Colors: Blue", 1993), { director: "Krzysztof Kieślowski", genres: ["Drama"], country: "Poland", lbAvg: 4.1 }],
  [k("Three Colors: Red", 1994), { director: "Krzysztof Kieślowski", genres: ["Drama", "Mystery", "Romance"], country: "Poland", lbAvg: 4.2 }],
  [k("Three Colors: White", 1994), { director: "Krzysztof Kieślowski", genres: ["Comedy", "Drama", "Romance"], country: "Poland", lbAvg: 3.7 }],
  [k("Ida", 2013), { director: "Paweł Pawlikowski", genres: ["Drama"], country: "Poland", lbAvg: 3.8 }],
  [k("Cold War", 2018), { director: "Paweł Pawlikowski", genres: ["Drama", "Romance"], country: "Poland", lbAvg: 4.0 }],

  // === IRANIAN CINEMA ===
  [k("Taste of Cherry", 1997), { director: "Abbas Kiarostami", genres: ["Drama"], country: "Iran", lbAvg: 3.9 }],
  [k("Close-Up", 1990), { director: "Abbas Kiarostami", genres: ["Drama", "Documentary"], country: "Iran", lbAvg: 4.2 }],
  [k("Certified Copy", 2010), { director: "Abbas Kiarostami", genres: ["Drama", "Romance"], country: "Iran", lbAvg: 3.9 }],
  [k("A Separation", 2011), { director: "Asghar Farhadi", genres: ["Drama"], country: "Iran", lbAvg: 4.3 }],

  // === SPANISH / LATIN AMERICAN ===
  [k("The Spirit of the Beehive", 1973), { director: "Víctor Erice", genres: ["Drama"], country: "Spain", lbAvg: 4.1 }],
  [k("Pan's Labyrinth", 2006), { director: "Guillermo del Toro", genres: ["Fantasy", "Drama", "War"], country: "Mexico", lbAvg: 4.2 }],
  [k("The Shape of Water", 2017), { director: "Guillermo del Toro", genres: ["Fantasy", "Drama", "Romance"], country: "USA", lbAvg: 3.6 }],
  [k("Roma", 2018), { director: "Alfonso Cuarón", genres: ["Drama"], country: "Mexico", lbAvg: 4.0 }],
  [k("Y Tu Mamá También", 2001), { director: "Alfonso Cuarón", genres: ["Drama", "Romance"], country: "Mexico", lbAvg: 3.9 }],
  [k("Children of Men", 2006), { director: "Alfonso Cuarón", genres: ["Sci-Fi", "Thriller", "Drama"], country: "UK", lbAvg: 4.1 }],
  [k("Gravity", 2013), { director: "Alfonso Cuarón", genres: ["Sci-Fi", "Thriller"], country: "USA", lbAvg: 3.5 }],
  [k("All About My Mother", 1999), { director: "Pedro Almodóvar", genres: ["Drama"], country: "Spain", lbAvg: 4.0 }],
  [k("Talk to Her", 2002), { director: "Pedro Almodóvar", genres: ["Drama"], country: "Spain", lbAvg: 4.0 }],
  [k("Pain and Glory", 2019), { director: "Pedro Almodóvar", genres: ["Drama"], country: "Spain", lbAvg: 3.8 }],

  // === GERMAN / AUSTRIAN ===
  [k("Metropolis", 1927), { director: "Fritz Lang", genres: ["Sci-Fi", "Drama"], country: "Germany", lbAvg: 4.2 }],
  [k("M", 1931), { director: "Fritz Lang", genres: ["Crime", "Thriller"], country: "Germany", lbAvg: 4.2 }],
  [k("Wings of Desire", 1987), { director: "Wim Wenders", genres: ["Drama", "Fantasy", "Romance"], country: "Germany", lbAvg: 4.1 }],
  [k("Paris, Texas", 1984), { director: "Wim Wenders", genres: ["Drama", "Road"], country: "Germany", lbAvg: 4.3 }],
  [k("The Lives of Others", 2006), { director: "Florian Henckel von Donnersmarck", genres: ["Drama", "Thriller"], country: "Germany", lbAvg: 4.3 }],
  [k("The Passion of Joan of Arc", 1928), { director: "Carl Theodor Dreyer", genres: ["Drama", "Historical"], country: "Denmark", lbAvg: 4.4 }],

  // === INDIAN CINEMA ===
  [k("Pather Panchali", 1955), { director: "Satyajit Ray", genres: ["Drama"], country: "India", lbAvg: 4.3 }],
  [k("The Apu Trilogy", 1959), { director: "Satyajit Ray", genres: ["Drama"], country: "India", lbAvg: 4.5 }],
  [k("RRR", 2022), { director: "S.S. Rajamouli", genres: ["Action", "Drama"], country: "India", lbAvg: 3.8 }],

  // === ANIMATION (NON-JAPANESE) ===
  [k("WALL·E", 2008), { director: "Andrew Stanton", genres: ["Animation", "Sci-Fi", "Romance"], country: "USA", lbAvg: 4.2 }],
  [k("Ratatouille", 2007), { director: "Brad Bird", genres: ["Animation", "Comedy", "Family"], country: "USA", lbAvg: 4.1 }],
  [k("The Incredibles", 2004), { director: "Brad Bird", genres: ["Animation", "Action", "Family"], country: "USA", lbAvg: 4.0 }],
  [k("Inside Out", 2015), { director: "Pete Docter", genres: ["Animation", "Comedy", "Drama"], country: "USA", lbAvg: 4.0 }],
  [k("Up", 2009), { director: "Pete Docter", genres: ["Animation", "Adventure", "Comedy"], country: "USA", lbAvg: 4.0 }],
  [k("Toy Story", 1995), { director: "John Lasseter", genres: ["Animation", "Comedy", "Family"], country: "USA", lbAvg: 4.0 }],
  [k("Finding Nemo", 2003), { director: "Andrew Stanton", genres: ["Animation", "Adventure", "Comedy"], country: "USA", lbAvg: 4.0 }],
  [k("Spider-Man: Into the Spider-Verse", 2018), { director: "Bob Persichetti", genres: ["Animation", "Action", "Adventure"], country: "USA", lbAvg: 4.3 }],
  [k("Spider-Man: Across the Spider-Verse", 2023), { director: "Joaquim Dos Santos", genres: ["Animation", "Action", "Adventure"], country: "USA", lbAvg: 4.2 }],
  [k("Coco", 2017), { director: "Lee Unkrich", genres: ["Animation", "Fantasy", "Music"], country: "USA", lbAvg: 4.1 }],

  // === MISC MODERN ESSENTIAL ===
  [k("The Lobster", 2015), { director: "Yorgos Lanthimos", genres: ["Comedy", "Drama", "Sci-Fi"], country: "Greece", lbAvg: 3.6 }],
  [k("The Favourite", 2018), { director: "Yorgos Lanthimos", genres: ["Comedy", "Drama", "History"], country: "UK", lbAvg: 3.9 }],
  [k("Poor Things", 2023), { director: "Yorgos Lanthimos", genres: ["Comedy", "Drama", "Sci-Fi"], country: "UK", lbAvg: 3.9 }],
  [k("Dogtooth", 2009), { director: "Yorgos Lanthimos", genres: ["Drama", "Thriller"], country: "Greece", lbAvg: 3.6 }],
  [k("The Killing of a Sacred Deer", 2017), { director: "Yorgos Lanthimos", genres: ["Drama", "Horror", "Thriller"], country: "UK", lbAvg: 3.5 }],
  [k("The Zone of Interest", 2023), { director: "Jonathan Glazer", genres: ["Drama", "History", "War"], country: "UK", lbAvg: 3.8 }],
  [k("Under the Skin", 2013), { director: "Jonathan Glazer", genres: ["Sci-Fi", "Horror"], country: "UK", lbAvg: 3.4 }],
  [k("Aftersun", 2022), { director: "Charlotte Wells", genres: ["Drama"], country: "UK", lbAvg: 4.0 }],
  [k("The Banshees of Inisherin", 2022), { director: "Martin McDonagh", genres: ["Comedy", "Drama"], country: "Ireland", lbAvg: 3.9 }],
  [k("Three Billboards Outside Ebbing, Missouri", 2017), { director: "Martin McDonagh", genres: ["Crime", "Drama"], country: "UK", lbAvg: 3.9 }],
  [k("In Bruges", 2008), { director: "Martin McDonagh", genres: ["Comedy", "Crime", "Drama"], country: "UK", lbAvg: 4.0 }],
  [k("Tár", 2022), { director: "Todd Field", genres: ["Drama", "Music"], country: "USA", lbAvg: 3.7 }],
  [k("The Power of the Dog", 2021), { director: "Jane Campion", genres: ["Drama", "Western"], country: "New Zealand", lbAvg: 3.4 }],
  [k("The Piano", 1993), { director: "Jane Campion", genres: ["Drama", "Romance"], country: "New Zealand", lbAvg: 3.7 }],
  [k("Trainspotting", 1996), { director: "Danny Boyle", genres: ["Crime", "Drama"], country: "UK", lbAvg: 4.1 }],
  [k("Requiem for a Dream", 2000), { director: "Darren Aronofsky", genres: ["Drama"], country: "USA", lbAvg: 4.1 }],
  [k("Black Swan", 2010), { director: "Darren Aronofsky", genres: ["Drama", "Thriller", "Horror"], country: "USA", lbAvg: 3.9 }],
  [k("The Wrestler", 2008), { director: "Darren Aronofsky", genres: ["Drama", "Sport"], country: "USA", lbAvg: 3.9 }],
  [k("Nightcrawler", 2014), { director: "Dan Gilroy", genres: ["Crime", "Thriller"], country: "USA", lbAvg: 4.0 }],
  [k("Ex Machina", 2014), { director: "Alex Garland", genres: ["Sci-Fi", "Drama", "Thriller"], country: "UK", lbAvg: 3.9 }],
  [k("The Prestige", 2006), { director: "Christopher Nolan", genres: ["Drama", "Mystery", "Thriller"], country: "USA", lbAvg: 4.2 }],
  [k("Batman Begins", 2005), { director: "Christopher Nolan", genres: ["Action", "Crime"], country: "USA", lbAvg: 3.9 }],
  [k("Tenet", 2020), { director: "Christopher Nolan", genres: ["Sci-Fi", "Action", "Thriller"], country: "USA", lbAvg: 3.2 }],
  [k("Joker", 2019), { director: "Todd Phillips", genres: ["Crime", "Drama", "Thriller"], country: "USA", lbAvg: 3.8 }],
  [k("1917", 2019), { director: "Sam Mendes", genres: ["War", "Drama"], country: "UK", lbAvg: 3.9 }],
  [k("American Beauty", 1999), { director: "Sam Mendes", genres: ["Drama"], country: "USA", lbAvg: 3.8 }],
  [k("The Lord of the Rings: The Fellowship of the Ring", 2001), { director: "Peter Jackson", genres: ["Fantasy", "Adventure"], country: "New Zealand", lbAvg: 4.4 }],
  [k("The Lord of the Rings: The Two Towers", 2002), { director: "Peter Jackson", genres: ["Fantasy", "Adventure"], country: "New Zealand", lbAvg: 4.3 }],
  [k("The Lord of the Rings: The Return of the King", 2003), { director: "Peter Jackson", genres: ["Fantasy", "Adventure"], country: "New Zealand", lbAvg: 4.5 }],
  [k("Jeanne Dielman, 23, quai du Commerce, 1080 Bruxelles", 1975), { director: "Chantal Akerman", genres: ["Drama", "Experimental"], country: "Belgium", lbAvg: 4.0 }],
  [k("All That Jazz", 1979), { director: "Bob Fosse", genres: ["Musical", "Drama"], country: "USA", lbAvg: 4.1 }],
  [k("The Passion of Joan of Arc", 1928), { director: "Carl Theodor Dreyer", genres: ["Drama", "Historical"], country: "Denmark", lbAvg: 4.4 }],
  [k("Nosferatu", 1922), { director: "F.W. Murnau", genres: ["Horror", "Fantasy"], country: "Germany", lbAvg: 3.9 }],
  [k("The Cabinet of Dr. Caligari", 1920), { director: "Robert Wiene", genres: ["Horror", "Mystery"], country: "Germany", lbAvg: 3.9 }],
  [k("Nosferatu", 2024), { director: "Robert Eggers", genres: ["Horror", "Drama"], country: "USA", lbAvg: 3.6 }],

  // === HORROR ESSENTIALS ===
  [k("The Texas Chain Saw Massacre", 1974), { director: "Tobe Hooper", genres: ["Horror"], country: "USA", lbAvg: 3.8 }],
  [k("Halloween", 1978), { director: "John Carpenter", genres: ["Horror", "Thriller"], country: "USA", lbAvg: 3.9 }],
  [k("The Thing", 1982), { director: "John Carpenter", genres: ["Horror", "Sci-Fi"], country: "USA", lbAvg: 4.2 }],
  [k("A Nightmare on Elm Street", 1984), { director: "Wes Craven", genres: ["Horror"], country: "USA", lbAvg: 3.6 }],
  [k("Scream", 1996), { director: "Wes Craven", genres: ["Horror", "Mystery", "Thriller"], country: "USA", lbAvg: 3.7 }],
  [k("Suspiria", 1977), { director: "Dario Argento", genres: ["Horror"], country: "Italy", lbAvg: 3.9 }],
  [k("The Babadook", 2014), { director: "Jennifer Kent", genres: ["Horror", "Drama"], country: "Australia", lbAvg: 3.4 }],
  [k("It Follows", 2014), { director: "David Robert Mitchell", genres: ["Horror", "Thriller"], country: "USA", lbAvg: 3.4 }],
  [k("The Blair Witch Project", 1999), { director: "Daniel Myrick", genres: ["Horror"], country: "USA", lbAvg: 3.1 }],
  [k("Rosemary's Baby", 1968), { director: "Roman Polanski", genres: ["Horror", "Drama"], country: "USA", lbAvg: 4.0 }],

  // === MORE MODERN HITS ===
  [k("The Batman", 2022), { director: "Matt Reeves", genres: ["Action", "Crime", "Drama"], country: "USA", lbAvg: 3.7 }],
  [k("Top Gun: Maverick", 2022), { director: "Joseph Kosinski", genres: ["Action", "Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Knives Out", 2019), { director: "Rian Johnson", genres: ["Comedy", "Crime", "Mystery"], country: "USA", lbAvg: 3.9 }],
  [k("Glass Onion: A Knives Out Mystery", 2022), { director: "Rian Johnson", genres: ["Comedy", "Crime", "Mystery"], country: "USA", lbAvg: 3.6 }],
  [k("Uncut Gems", 2019), { director: "Josh Safdie", genres: ["Crime", "Thriller", "Drama"], country: "USA", lbAvg: 3.8 }],
  [k("Good Time", 2017), { director: "Josh Safdie", genres: ["Crime", "Thriller"], country: "USA", lbAvg: 3.9 }],
  [k("Marriage Story", 2019), { director: "Noah Baumbach", genres: ["Drama", "Romance"], country: "USA", lbAvg: 3.9 }],
  [k("The Substance", 2024), { director: "Coralie Fargeat", genres: ["Horror", "Drama", "Sci-Fi"], country: "France", lbAvg: 3.7 }],
  [k("The Brutalist", 2024), { director: "Brady Corbet", genres: ["Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Conclave", 2024), { director: "Edward Berger", genres: ["Drama", "Thriller"], country: "UK", lbAvg: 3.7 }],
  [k("All Quiet on the Western Front", 2022), { director: "Edward Berger", genres: ["War", "Drama"], country: "Germany", lbAvg: 3.9 }],
  [k("Emilia Pérez", 2024), { director: "Jacques Audiard", genres: ["Musical", "Drama", "Crime"], country: "France", lbAvg: 2.7 }],
  [k("A Real Pain", 2024), { director: "Jesse Eisenberg", genres: ["Comedy", "Drama"], country: "USA", lbAvg: 3.7 }],
  [k("Challengers", 2024), { director: "Luca Guadagnino", genres: ["Drama", "Romance", "Sport"], country: "USA", lbAvg: 3.8 }],
  [k("Call Me by Your Name", 2017), { director: "Luca Guadagnino", genres: ["Romance", "Drama"], country: "Italy", lbAvg: 3.9 }],
  [k("Brokeback Mountain", 2005), { director: "Ang Lee", genres: ["Romance", "Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Life of Pi", 2012), { director: "Ang Lee", genres: ["Adventure", "Drama", "Fantasy"], country: "USA", lbAvg: 3.7 }],
  [k("Promising Young Woman", 2020), { director: "Emerald Fennell", genres: ["Crime", "Drama", "Thriller"], country: "UK", lbAvg: 3.6 }],
  [k("Saltburn", 2023), { director: "Emerald Fennell", genres: ["Comedy", "Drama", "Thriller"], country: "UK", lbAvg: 3.1 }],
  [k("The Holdovers", 2023), { director: "Alexander Payne", genres: ["Comedy", "Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Sideways", 2004), { director: "Alexander Payne", genres: ["Comedy", "Drama", "Romance"], country: "USA", lbAvg: 3.7 }],
  [k("The Fabelmans", 2022), { director: "Steven Spielberg", genres: ["Drama"], country: "USA", lbAvg: 3.7 }],
  [k("West Side Story", 2021), { director: "Steven Spielberg", genres: ["Musical", "Drama", "Romance"], country: "USA", lbAvg: 3.7 }],
  [k("Nope", 2022), { director: "Jordan Peele", genres: ["Horror", "Sci-Fi", "Mystery"], country: "USA", lbAvg: 3.3 }],
  [k("Minari", 2020), { director: "Lee Isaac Chung", genres: ["Drama"], country: "USA", lbAvg: 3.8 }],
  [k("Nomadland", 2020), { director: "Chloé Zhao", genres: ["Drama"], country: "USA", lbAvg: 3.5 }],
  [k("The Father", 2020), { director: "Florian Zeller", genres: ["Drama"], country: "UK", lbAvg: 4.2 }],
  [k("Sound of Metal", 2019), { director: "Darius Marder", genres: ["Drama", "Music"], country: "USA", lbAvg: 3.9 }],
  [k("Phantom Thread", 2017), { director: "Paul Thomas Anderson", genres: ["Drama", "Romance"], country: "USA", lbAvg: 3.8 }],
  [k("Manchester by the Sea", 2016), { director: "Kenneth Lonergan", genres: ["Drama"], country: "USA", lbAvg: 3.9 }],
  [k("Room", 2015), { director: "Lenny Abrahamson", genres: ["Drama", "Thriller"], country: "Ireland", lbAvg: 4.1 }],
  [k("Spotlight", 2015), { director: "Tom McCarthy", genres: ["Crime", "Drama"], country: "USA", lbAvg: 4.1 }],
  [k("Birdman", 2014), { director: "Alejandro González Iñárritu", genres: ["Comedy", "Drama"], country: "USA", lbAvg: 3.8 }],
  [k("The Revenant", 2015), { director: "Alejandro González Iñárritu", genres: ["Adventure", "Drama", "Western"], country: "USA", lbAvg: 3.7 }],
  [k("Amores Perros", 2000), { director: "Alejandro González Iñárritu", genres: ["Crime", "Drama", "Thriller"], country: "Mexico", lbAvg: 4.0 }],
  [k("Babel", 2006), { director: "Alejandro González Iñárritu", genres: ["Drama"], country: "Mexico", lbAvg: 3.6 }],
  [k("12 Years a Slave", 2013), { director: "Steve McQueen", genres: ["Drama", "History"], country: "UK", lbAvg: 4.1 }],
  [k("Shame", 2011), { director: "Steve McQueen", genres: ["Drama"], country: "UK", lbAvg: 3.7 }],
  [k("Hunger", 2008), { director: "Steve McQueen", genres: ["Drama"], country: "UK", lbAvg: 3.8 }],
  [k("Dunkirk", 2017), { director: "Christopher Nolan", genres: ["War", "Drama", "Action"], country: "UK", lbAvg: 3.8 }],
]);

// Country to flag emoji mapping
export const COUNTRY_FLAGS: Record<string, string> = {
  "USA": "🇺🇸",
  "UK": "🇬🇧",
  "France": "🇫🇷",
  "Italy": "🇮🇹",
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Germany": "🇩🇪",
  "Russia": "🇷🇺",
  "Sweden": "🇸🇪",
  "Spain": "🇪🇸",
  "Mexico": "🇲🇽",
  "Iran": "🇮🇷",
  "Poland": "🇵🇱",
  "India": "🇮🇳",
  "Taiwan": "🇹🇼",
  "Hong Kong": "🇭🇰",
  "China": "🇨🇳",
  "Australia": "🇦🇺",
  "Denmark": "🇩🇰",
  "Austria": "🇦🇹",
  "Ireland": "🇮🇪",
  "Belgium": "🇧🇪",
  "New Zealand": "🇳🇿",
  "Norway": "🇳🇴",
  "Greece": "🇬🇷",
};

// Non-English speaking countries
export const NON_ENGLISH_COUNTRIES = new Set([
  "France", "Italy", "Japan", "South Korea", "Germany", "Russia", "Sweden",
  "Spain", "Mexico", "Iran", "Poland", "India", "Taiwan", "Hong Kong",
  "China", "Denmark", "Austria", "Belgium", "Norway", "Greece",
]);

export function lookupFilm(name: string, year: number): FilmMeta | undefined {
  return FILM_METADATA.get(`${name.toLowerCase()}-${year}`);
}
